### ISSUE TITLE
get_sinks outdated cache

### ISSUE THREAD

**Issue by danclimasevschi** [wirepas/wirepas-mqtt-library#3]
If a sink configuration is updated via `set_sink_config` method, the following calls to `get_sinks` will return old cached configurations. I did not use a callback so the execution was synchronous(I also tried with a callback and calling `get_sinks` from there, but I still got old data).
As a workaround I used `set_config_changed_cb` to listen for changes and run subsequent calls to `get_gateways` and `get_sinks` in order to get latest sink configuration.

**Comment by GwendalRaoul** [comment]
Hello,
You are correct. When getting the answer form the set config, the new sink config is included in response so it is quite trivial to update the cached version.
I made a patch for it and will publish it as soon as I made more testing on it.

Thanks!
